/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIaRouteImport } from './routes/agents-ia'
import { Route as CasClientsRouteImport } from './routes/cas-clients'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as TarifsRouteImport } from './routes/tarifs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIaRoute = AgentsIaRouteImport.update({
  id: '/agents-ia',
  path: '/agents-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const CasClientsRoute = CasClientsRouteImport.update({
  id: '/cas-clients',
  path: '/cas-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents-ia': typeof AgentsIaRoute
  '/cas-clients': typeof CasClientsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents-ia': typeof AgentsIaRoute
  '/cas-clients': typeof CasClientsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents-ia': typeof AgentsIaRoute
  '/cas-clients': typeof CasClientsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents-ia'
    | '/cas-clients'
    | '/confidentialite'
    | '/contact'
    | '/fonctionnalites'
    | '/mentions-legales'
    | '/tarifs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents-ia'
    | '/cas-clients'
    | '/confidentialite'
    | '/contact'
    | '/fonctionnalites'
    | '/mentions-legales'
    | '/tarifs'
  id:
    | '__root__'
    | '/'
    | '/agents-ia'
    | '/cas-clients'
    | '/confidentialite'
    | '/contact'
    | '/fonctionnalites'
    | '/mentions-legales'
    | '/tarifs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsIaRoute: typeof AgentsIaRoute
  CasClientsRoute: typeof CasClientsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-ia': {
      id: '/agents-ia'
      path: '/agents-ia'
      fullPath: '/agents-ia'
      preLoaderRoute: typeof AgentsIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cas-clients': {
      id: '/cas-clients'
      path: '/cas-clients'
      fullPath: '/cas-clients'
      preLoaderRoute: typeof CasClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsIaRoute: AgentsIaRoute,
  CasClientsRoute: CasClientsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
